const Translator = keyword =>{
  const dictionary = {
    "갈비찜" : "gal-bi-jjim",
    "국밥" : "guk-bab",
    "국수": "korean-noodle",
    "김밥" : "kim-bab", 
    "김치볶음밥" : "kimchi-fried-rice", 
    "김치찜": "kimchi-jjim", 
    "냉면": "naeng-myeon", 
    "닭갈비": "chicken-galbi",
    "닭볶음탕": "chicken-fried-tang", 
    "도시락": "do-si-rak", 
    "돈까스": "pork-cutlet", 
    "떡볶이": "ddeok-bok-i", 
    "라멘": "ramen", 
    "라면": "korean-instant-noodle", 
    "리소토": "risotto", 
    "보쌈": "bo-ssam", 
    "볶음밥": "fried-rice",
    "분식": "bun-sik", 
    "불고기": "bul-gogi", 
    "비빔밥": "bi-bim-bab", 
    "삼계탕": "sam-gye-tang", 
    "샌드위치": "sandwich", 
    "생선구이": "baked-fish", 
    "수제비": "su-je-bi", 
    "순대": "sun-dae", 
    "스테이크": "steak", 
    "쌀국수": "rice-noodle", 
    "알밥": "al-bab", 
    "양꼬치": "lamb-skewer", 
    "연어덮밥": "raw-salmon-rice", 
    "우동": "udon", 
    "월남쌈": "vietnamese-spring-rolls", 
    "제육볶음": "stir-fried-spicy-fork",
    "짬뽕": "jjam-bbong", 
    "쭈꾸미": "jjukumi", 
    "찌개": "jji-gae", 
    "찜닭": "jjim-chicken", 
    "초밥": "sushi", 
    "추어탕": "chu-eo-tang", 
    "치킨": "fried-chicken", 
    "칼국수": "kal-guk-su", 
    "타코": "taco", 
    "탕수육": "tang-su-yook", 
    "파스타": "pasta", 
    "팟타이": "pat-thai", 
    "피자": "pizza", 
    "한정식": "korean-table", 
    "해장국": "hae-jang-guk", 
    "햄버거": "hamburger",
  }
  return dictionary[keyword] ? dictionary[keyword] : keyword;
}

export default Translator;