import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { shareKakao } from './kakao/shareKakao';
import initialize from './kakao/initialize';

export default function Home() {

  useEffect(() => {
    // useEffect() 는 초기 빌드에는 실행되지 않으므로
    // 처음 ssr시에는 window 객체를 불러오지 않도록
    initialize();
  }, []);

  const menus = ['햄버거', '라면', '한식', '중식', '양식', '냉면'];

  // [state(ui 바뀌는)변수, 해당 변수를 갱신하는 함수]
  const [items, setItems] = useState(['눌러서 확인하기']);
  const [links, setLinks] = useState(["https://map.naver.com/v5/search/"]);

  const clickHandler = () => {
    var selected = menus[Math.floor(Math.random() * menus.length)];
    setItems(selected);
    var selectedLink = "https://map.naver.com/v5/search/" + selected;
    setLinks(selectedLink);
  }

  const clickHandlerKakao = () => {
    if (typeof window != 'undefined') {
      const title = items;
      const sharelink = links;
      // console.log(title, sharelink);
      shareKakao(title, sharelink);
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>오늘 점심 뭐먹지?</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          오늘 점심은 뭐 먹지?
        </h1>

        <p className={styles.description}>
          <code onClick={clickHandler} className={styles.code}>{items}</code>
        </p>

        <div className={styles.grid}>
          <a onClick={clickHandler} className={styles.card}>
            <h2>다시 돌리기 &rarr;</h2>
            {/* <p>Find in-depth information about Next.js features and API.</p> */}
          </a>

          <a href={links} target="_blank" className={styles.card}>
            <h2>검색하기 &rarr;</h2>
            {/* <p>Learn about Next.js in an interactive course with quizzes!</p> */}
          </a>
          <a onClick={clickHandlerKakao} className={styles.card}>
            <h2>공유하기 &rarr;</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
